"""add ai run mode

Revision ID: 12925cf8034b
Revises: ebe76b2f44f6
Create Date: 2026-07-17 03:24:49.071189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12925cf8034b'
down_revision: Union[str, Sequence[str], None] = 'ebe76b2f44f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_runs', sa.Column('mode', sa.Enum('chat', 'agent', name='ai_run_mode', native_enum=False, create_constraint=True, length=20), server_default='chat', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_runs', 'mode')
    # ### end Alembic commands ###
