"""create knowledge documents and sync jobs

Revision ID: a9a745d5e1e7
Revises: 12925cf8034b
Create Date: 2026-07-17 05:49:07.854853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a745d5e1e7'
down_revision: Union[str, Sequence[str], None] = '12925cf8034b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=150), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'deleted', name='knowledge_document_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('dify_document_id', sa.String(length=36), nullable=True),
    sa.Column('dify_indexing_status', sa.String(length=32), nullable=True),
    sa.Column('latest_error_code', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_knowledge_documents_knowledge_document_size_positive')),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_knowledge_documents_deleted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_knowledge_documents_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('dify_document_id', name='uq_knowledge_documents_dify_document_id'),
    sa.UniqueConstraint('storage_key', name='uq_knowledge_documents_storage_key')
    )
    op.create_index('ix_knowledge_documents_tenant_deleted_created', 'knowledge_documents', ['tenant_id', 'deleted_at', 'created_at'], unique=False)
    op.create_index('ix_knowledge_documents_tenant_status_created', 'knowledge_documents', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_uploaded_by_user_id'), 'knowledge_documents', ['uploaded_by_user_id'], unique=False)
    op.create_table('knowledge_sync_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.Enum('upload', 'reindex', 'delete', name='knowledge_sync_operation', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='knowledge_sync_job_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('dify_batch_id', sa.String(length=64), nullable=True),
    sa.Column('dify_indexing_status', sa.String(length=32), nullable=True),
    sa.Column('completed_segments', sa.Integer(), nullable=True),
    sa.Column('total_segments', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_segments IS NULL OR completed_segments >= 0', name=op.f('ck_knowledge_sync_jobs_knowledge_sync_completed_segments_non_negative')),
    sa.CheckConstraint('completed_segments IS NULL OR total_segments IS NULL OR completed_segments <= total_segments', name=op.f('ck_knowledge_sync_jobs_knowledge_sync_completed_not_above_total')),
    sa.CheckConstraint('total_segments IS NULL OR total_segments >= 0', name=op.f('ck_knowledge_sync_jobs_knowledge_sync_total_segments_non_negative')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_knowledge_sync_jobs_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_sync_jobs_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sync_jobs'))
    )
    op.create_index(op.f('ix_knowledge_sync_jobs_created_by_user_id'), 'knowledge_sync_jobs', ['created_by_user_id'], unique=False)
    op.create_index('ix_knowledge_sync_jobs_document_created', 'knowledge_sync_jobs', ['document_id', 'created_at'], unique=False)
    op.create_index('ix_knowledge_sync_jobs_tenant_status_created', 'knowledge_sync_jobs', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index('uq_knowledge_sync_jobs_active_document', 'knowledge_sync_jobs', ['document_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing')"), sqlite_where=sa.text("status IN ('pending', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_knowledge_sync_jobs_active_document', table_name='knowledge_sync_jobs', postgresql_where=sa.text("status IN ('pending', 'processing')"), sqlite_where=sa.text("status IN ('pending', 'processing')"))
    op.drop_index('ix_knowledge_sync_jobs_tenant_status_created', table_name='knowledge_sync_jobs')
    op.drop_index('ix_knowledge_sync_jobs_document_created', table_name='knowledge_sync_jobs')
    op.drop_index(op.f('ix_knowledge_sync_jobs_created_by_user_id'), table_name='knowledge_sync_jobs')
    op.drop_table('knowledge_sync_jobs')
    op.drop_index(op.f('ix_knowledge_documents_uploaded_by_user_id'), table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_tenant_status_created', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_tenant_deleted_created', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
