"""track knowledge deletion phases

Revision ID: db5ec0516aa8
Revises: a9a745d5e1e7
Create Date: 2026-07-17 06:21:35.431389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5ec0516aa8'
down_revision: Union[str, Sequence[str], None] = 'a9a745d5e1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_sync_jobs', sa.Column('dify_deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_sync_jobs', sa.Column('file_deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_sync_jobs', 'file_deleted_at')
    op.drop_column('knowledge_sync_jobs', 'dify_deleted_at')
    # ### end Alembic commands ###
