"""create ai runs

Revision ID: ebe76b2f44f6
Revises: 208539977b2b
Create Date: 2026-07-17 02:17:59.211903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe76b2f44f6'
down_revision: Union[str, Sequence[str], None] = '208539977b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'cancelled', name='ai_run_status', native_enum=False, create_constraint=True, length=20), server_default='running', nullable=False),
    sa.Column('prompt_message_id', sa.Uuid(), nullable=True),
    sa.Column('response_message_id', sa.Uuid(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_ai_runs_ai_run_input_tokens_non_negative')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_ai_runs_ai_run_output_tokens_non_negative')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_ai_runs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_message_id'], ['messages.id'], name=op.f('fk_ai_runs_prompt_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_message_id'], ['messages.id'], name=op.f('fk_ai_runs_response_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs')),
    sa.UniqueConstraint('tenant_id', 'user_id', 'request_id', name='uq_ai_runs_owner_request_id')
    )
    op.create_index('ix_ai_runs_conversation_created', 'ai_runs', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_runs_conversation_id'), 'ai_runs', ['conversation_id'], unique=False)
    op.create_index('ix_ai_runs_owner_created', 'ai_runs', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_runs_request_id'), 'ai_runs', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_tenant_id'), 'ai_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_user_id'), 'ai_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_runs_user_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_tenant_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_request_id'), table_name='ai_runs')
    op.drop_index('ix_ai_runs_owner_created', table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_conversation_id'), table_name='ai_runs')
    op.drop_index('ix_ai_runs_conversation_created', table_name='ai_runs')
    op.drop_table('ai_runs')
    # ### end Alembic commands ###
